#!/bin/sh -e

RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${YELLOW}Cleaning up old system generations...${NC}"

# Remove generations older than 1 day (reclaim space)
sudo nix-collect-garbage --delete-older-than 1d

echo -e "${GREEN}Cleanup complete!${NC}"