# ============================================================================
# PLACEHOLDER — REPLACE ON THE REAL LAPTOP.
#
# This is a template so the flake still evaluates. The device paths/UUIDs and
# the exact kernel modules below are GUESSES and almost certainly wrong for
# your hardware. Do NOT `nixos-rebuild` against this as-is.
#
# On the Intel laptop, after partitioning/installing, run:
#     sudo nixos-generate-config --show-hardware-config > \
#       /etc/nixos/hardware-configuration.nix
# then copy that output over this file (keep the filename/location).
# ============================================================================
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  # Typical Intel laptop boot/storage modules — regenerate to get the real set.
  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # PLACEHOLDER filesystems — replace with the generated by-uuid entries.
  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/boot";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted
  # networking the default is to use DHCP per-interface.
  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
